src/objects/Stripe_Data__c.object
<CustomObject>
    <description>Receives and Retrieves Data from Stripe WebHook</description>
    <fields>
        <fullName>JSON_Response__c</fullName>
        <label>JSON Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Verify Data from Stripe</fullName>
                </value>
                <value>
                    <fullName>Verified Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Verification</fullName>
                </value>
                <value>
                    <fullName>Imported Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Import</fullName>
                </value>
                <value>
                    <fullName>Processed Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stripe_Event_Type__c</fullName>
        <label>Stripe Event Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stripe_Live_Mode__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was this transaction a live Stripe Transaction?</description>
        <inlineHelpText>Was this transaction a live Stripe Transaction?</inlineHelpText>
        <label>Stripe Live Mode?</label>
        <type>Checkbox</type>
    </fields>
    <label>Stripe Data</label>
    <nameField>
        <displayFormat>STRIPE-{000000}</displayFormat>
        <label>Stripe Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StripeWebhookListener2.cls
public virtual class StripeWebhookListener2 {
   Stripe_Data__c stripedata;

    public String handleGet() {
        return 'OK';
    }

    public void handlePost() {
        RestResponse response = RestContext.response;
        response.addHeader('Content-type','application/json');
        System.debug(System.LoggingLevel.INFO, '\n**** '+RestContext.request.requestBody.toString());

        try {
            
            Map<String, Object> m = (Map<String, Object>)json.deserializeUntyped(RestContext.request.requestBody.toString());
            system.debug(m);
            stripedata = new Stripe_Data__c();
            stripedata.stripe_npo__Stripe_Id__c = (String)m.get('id');
            stripedata.Stripe_Event_Type__c = (String)m.get('type');
            stripedata.Processing_Status__c = 'Verify Data from Stripe';
            stripedata.Stripe_Live_Mode__c =  (Boolean)m.get('livemode');
            
            stripedata.JSON_Response__c = RestContext.request.requestBody.toString();
            
            }
        catch (System.Exception e) {
                System.debug(System.LoggingLevel.INFO, '\n**** Exception: '+e); 
    
                Map<String, String> error = new Map<String, String>{
                    'type' => e.getTypeName(), 
                    'error' => e.getMessage()
                };
                response.responseBody = Blob.valueOf(JSON.serializePretty(error));
                response.statusCode = 500;
                return;
            }

        // prevent tests from hitting production
        if (stripedata.Stripe_Live_Mode__c == false && StripeAPI.isTest == false) {
            System.debug(System.LoggingLevel.INFO, '\n**** Bailing out'); 
            return;
        }

        System.debug(System.LoggingLevel.INFO, '\n**** Event Type in Listener: '+stripedata.Stripe_Event_Type__c); 

        try {
               
                upsert stripedata stripe_npo__Stripe_Id__c ;
                response.responseBody = Blob.valueOf(JSON.serializePretty(stripedata));
                response.statusCode = 200;
                return;
           
            }
        catch (Exception Ex) {
        system.debug(Ex);
        response.responseBody = Blob.valueOf(ex.getMessage());
        response.statusCode = 200;
        return;
        }
       }    
}