src/objects/Stripe_Data__c.object
<CustomObject>
    <description>Receives and Retrieves Data from Stripe WebHook</description>
    <fields>
        <fullName>JSON_Response__c</fullName>
        <label>JSON Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Verify Data from Stripe</fullName>
                </value>
                <value>
                    <fullName>Verified Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Verification</fullName>
                </value>
                <value>
                    <fullName>Imported Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Import</fullName>
                </value>
                <value>
                    <fullName>Processed Successfully</fullName>
                </value>
                <value>
                    <fullName>Error with Processing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stripe_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Stripe Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Stripe Data</label>
    <nameField>
        <displayFormat>STRIPE-{000000}</displayFormat>
        <label>Stripe Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StripeDataControllerExtension.cls
public class StripeDataControllerExtension {

    public StripeWebhookRetrieval webhook {get;set;}
	private final Stripe_Data__c stripedata;
    private String sWebhookResponse;
    StripeMetaDataUtility scmd;

    public StripeDataControllerExtension (ApexPages.StandardController stdController) {
    	this.stripedata = (Stripe_Data__c)stdController.getRecord();
        scmd = new StripeMetaDataUtility();
    }

    public pagereference getStripeData () {
        webhook = new StripeWebhookRetrieval();
        Boolean bValid = webhook.getEventById(stripedata.Stripe_Id__c);

        if (bValid == TRUE) {
            stripedata.JSON_Response__c = webhook.response;
            stripedata.Processing_Status__c = 'Verified Successfully';
        }
        else {
            stripedata.Processing_Status__c = 'Error with Verification';

        }
        update stripedata;
        return null;
    }
    
    public pagereference executeLocalUpdate () {
        try{
            scmd.stripedata = this.stripedata;
            scmd.parseStripeEvent();
            stripedata.Processing_Status__c = 'Imported Successfully';
        }
        catch (Exception Ex) {
            system.debug(ex);
            stripedata.Processing_Status__c = 'Error with Import';
        }
        update stripedata;
        return null;
    }

}